"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.paymentWebhook = void 0;
const functions = __importStar(require("firebase-functions/v2"));
const admin = __importStar(require("firebase-admin"));
const rentalEngine_1 = require("./rentalEngine");
const db = admin.firestore();
exports.paymentWebhook = functions.https.onRequest(async (request, response) => {
    try {
        // 1. Verifikasi Signature & Payload (Disesuaikan dengan provider, misal: Midtrans/Xendit)
        const { orderId, status, secretKey } = request.body;
        // Dummy validation
        if (secretKey !== 'MY_SECRET_KEY') {
            response.status(403).send('Unauthorized');
            return;
        }
        if (status !== 'PAID') {
            response.status(200).send('Ignored: Status not PAID');
            return;
        }
        // 2. Ambil data Order dari Firestore
        const orderRef = db.collection('orders').doc(orderId);
        const orderSnap = await orderRef.get();
        if (!orderSnap.exists) {
            response.status(404).send('Order not found');
            return;
        }
        const order = orderSnap.data();
        if (order?.status === 'PAID') {
            response.status(200).send('Already processed');
            return;
        }
        // 3. Ambil data Product dan Package untuk detail akses dan durasi
        // Pada aslinya, data akses mungkin digenerate (misal: generate license key)
        // Di sini kita mock up akses datanya
        const dummyAccessData = {
            type: 'ACCOUNT',
            username: `user_${orderId}@flashrent.com`,
            password: 'AutoGeneratedPassword123!',
            instructions: 'Silakan login di website resmi.'
        };
        // 4. Update status Order menjadi PAID
        await orderRef.update({
            status: 'PAID',
            updatedAt: new Date().toISOString()
        });
        // 5. Memicu RentalEngine untuk membuat objek Rental aktif
        const rentalPayload = {
            orderId: orderId,
            userId: order?.userId || 'GUEST',
            productId: order?.productId,
            packageId: order?.packageId,
            // Asumsi package ada di order doc (simplified)
            durationType: order?.packageDurationType || 'LIMITED',
            durationValue: order?.packageDurationValue || 30,
            durationUnit: order?.packageDurationUnit || 'DAYS',
            accessData: dummyAccessData
        };
        await rentalEngine_1.RentalEngine.createRental(rentalPayload);
        response.status(200).send('Success: Order PAID & Rental Created');
    }
    catch (error) {
        console.error('Webhook Error:', error);
        response.status(500).send('Internal Server Error');
    }
});
//# sourceMappingURL=webhook.js.map